### PR TITLE
corrección de traducción 

### PR DESCRIPTION
**Pull request by jowasp**
Small changes to the translation/corrections

### CODE REVIEW

**Comment by soapdog** [comment]
Friends,

My Spanish is not as good as I would like it to be. Can we get an OK here from both of you if we should merge this one or not? Are the L10N corrections here neutral or not?

Thanks a lot for the awesome work you've all been doing.

**Comment by jowasp** [comment]
I think is OK

**Comment by leonardoruilova** [comment]
Hi, well I agree with @RAVMN about some strings changes here are more some kind of miscorrections than something else. But on the other side, there are also some good suggestions.  It is a bit difficult to choose via Github comments which ones to keep and which ones to discard. @soapdog, how can we apply just some of the strings changes suggested in this request?

**Comment by soapdog** [comment]
You can decide which strings you want to apply and change back the others and then commit again and push, the pull request should reflect your latest changes (I think)

**Comment by RAVMN** [comment]
Hi @soapdog, I will meet with the rest of the l10n team tomorrow and will select wich changes we are going to mantain (I think that it should be a fork from the fork that @jowasp did).

**Comment by soapdog** [comment]
Thanks a lot for the hard work my friends! :smile_cat: you're all awesome!

**Pull request merged**
